Add semantic-release as action
codeoverflow-org/nodecg-io-cli pull request #3
Opened 2021-04-15 19:59 UTC by ExtremTechniker

Add semantic-release.

Followed documentation on [github-actions.md](https://github.com/semantic-release/semantic-release/blob/1405b94296059c0c6878fb8b626e2c5da9317632/docs/recipes/github-actions.md)
and https://semantic-release.gitbook.io/semantic-release/usage/configuration

Please check on functionality.

2021-04-16 13:59 UTC, daniel0611 requested changes

2021-04-16 13:59 UTC, daniel0611 commented on .github/workflows/release.yml
> +        run: npm ci
We'll also need to build the TypeScript code here (`npm run build`) so that the `.js` files are present and will be included in the npm package.

2021-04-16 13:59 UTC, daniel0611 commented on package.json
> +  "name": "nodecg-io-cli",
Would be nice if you could switch the identation back to four spaces, as it is configured in our `.prettierrc.js` and done everywhere else in the repo :wink:

2021-04-16 13:59 UTC, daniel0611 commented on .releaserc
> +    ]
Could we also get [semantic-release/git](https://github.com/semantic-release/git) add here so it creates commits which update the version number after each release and pushes them? That would be nice :smiley:

2021-05-06 10:32 UTC, daniel0611 commented
@ExtremTechniker friendly ping :wink:. Do you still plan to work on this PR or shall I do the rest?

2021-05-06 18:48 UTC, ExtremTechniker commented
Hey. Sorry but at the moment I don't have any time to work on nodecg-io

2021-05-06 19:12 UTC, daniel0611 commented
Sure, no problem! Will finish this once I'm done with #11 (approximately tommorow).

2021-05-07 15:25 UTC, daniel0611 approved these changes

2021-05-07 15:25 UTC, merged

2021-05-07 15:58 UTC, daniel0611 commented
`0.1.0` will be released tomorrow because I didn't know it will always start at `1.0.0` instead of the current version by default and we need to wait 24h npm unpublishing limit.